DjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from first_app import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("first_app.urls")),
]

handler404 = views.page_not_found

first_app/urls.py
from django.conf.urls import handler404
from django.urls import path, register_converter
from first_app import views, converters

register_converter(converters.FourDigitYearConverter, 'year4')

app_name = 'first_app'

urlpatterns = [
    path(
        '',
        views.index,
        name='index',
    ),
    path(
        'books/',
        views.list_books,
        name='list_books',
    ),
    path(
        'books/<int:pk>/',
        views.book_detail,
        name='book_detail',
    ),
    path(
        'years/<year4:year>/',
        views.years,
        name='years',
    ),
    path(
        'get_params/',
        views.get_params,
        name='get_params',
    ),
    path(
        'redirect',
        views.redirect_view,
        name='redirect',
    ),
    path(
        'template',
        views.template,
        name='template',
    ),
    path(
        'custom_tags',
        views.custom_tags,
        name='custom_tags',
    ),
    path(
        'categories/',
        views.categories_list,
        name='categories_list',
    ),
    path(
        'category_detail/<slug:category_slug>/',
        views.category_detail,
        name='category_detail',
    ),
    path(
        'product/<slug:product_slug>',
        views.product_detail,
        name='product_detail',
    ),
]

first_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class ActiveProductsManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_active=True)


class Product(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.FloatField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    tags = models.ManyToManyField('ProductTag', blank=True, related_name='tags')
    one_to_one = models.OneToOneField(
        'SomeEntity',
        on_delete=models.SET_NULL,
        null=True,
        related_name='one_to_one',
    )

    objects = models.Manager()
    active_objects = ActiveProductsManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('first_app:product_detail', kwargs={'product_slug': self.slug})


class SomeEntity(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)


class ProductTag(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=100, unique=True, db_index=True)

    def __str__(self):
        return self.title

first_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound, Http404

from first_app.models import Category, Product


# Create your views here.
def index(request):
    return HttpResponse("Hello, world!")


def list_books(request):
    return HttpResponse("Books Page")


def book_detail(request, pk):
    return HttpResponse(f"Page of Book #{pk}")


def years(request, year):
    if year > 2025:
        raise Http404("Год должен быть меньше 2025")
    return HttpResponse(f"Year of Book #{year}")


def get_params(request):
    if request.GET:
        print(request.GET)
    return HttpResponse(
        ", ".join([f"{param} = {value}" for param, value in request.GET.items()])
    )


def redirect_view(request):
    return redirect('first_app:index', permanent=True)  # Можно указать view
    # return redirect('name', 'param')
    # return redirect(reverse('name', args=('param',))
    # HttpResponseRedirect, HttpResponsePermanentRedirect


def page_not_found(request, exception):
    return HttpResponseNotFound(f"404 Page not found: {exception}")


def template(request):
    context = {
        'users': [
            {'name': 'Max', 'age': 30, 'phone': '79998887766'},
            {'name': 'Alex', 'age': 25, 'phone': '78887776655'},
            {'name': 'Denis', 'age': 35, 'phone': '71234567890'},
        ]
    }
    return render(request, 'first_app/template.html', context)


def custom_tags(request):
    return render(request, 'first_app/custom_tags.html')


def categories_list(request):
    context = {'categories': Category.objects.all()}
    return render(request, 'first_app/categories.html', context)


def category_detail(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    context = {
        'category': get_object_or_404(Category, slug=category_slug),
        'products': Category.objects.get(slug=category_slug).product_set.all(),
        'active_products': Product.active_objects.filter(category=category),
    }
    return render(request, 'first_app/category.html', context)


def product_detail(request, product_slug):
    prod = get_object_or_404(Product, slug=product_slug)
    return render(
        request,
        'first_app/product_detail.html',
        {'product': prod},
    )

templates/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <title>{% block page_title %}Title{% endblock %}</title>
</head>
<body>
<h1>{% block page_header %}{% endblock %}</h1>
{% block content %}

{% endblock %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/first_app/categories.html
{% extends 'base.html' %}

{% block page_title %}
	{{ block.super }} Categories
{% endblock %}

{% block page_header %}
	Categories
{% endblock %}

{% block content %}
  {% if categories %}
    <ul>
    {% for category in categories %}
    <li><a href="{% url 'first_app:category_detail' category.slug %}">{{ category.title }}</a></li>
    {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/first_app/category.html
{% extends 'base.html' %}

{% block page_title %}
	{{ block.super }} {{ category.title }}
{% endblock %}

{% block page_header %}
	{{ category.title }}
{% endblock %}

{% block content %}
  <ul>
  <li>{{ category.title }}</li>
  <li>{{ category.description }}</li>
  </ul>
  {% if products %}
  	<ul>Products
    {% for product in active_products %}
    	<li>
        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
        {% if product.tags %}
          {% with  product.tags.all as tags %}
            {% for tag in tags %}
              {{ tag.title }}
            {% endfor %}
          {% endwith %}
        {% endif %}
      </li>
    {% endfor %}

    </ul>
  {% endif %}
{% endblock %}

templates/first_app/custom_tags.html
{% extends 'base.html' %}

{% block page_title %}
	{{ block.super }} Custom Tags
{% endblock %}

{% block page_header %}
	Custom tags
{% endblock %}

{% block content %}
  {% load simple_tags %}
  {% menu_tag as menu_items %}
  <ul>
  {% for menu_item in menu_items %}
    <li><a href="{{ menu_item.url }}">{{ menu_item.title }}</a></li>
  {% endfor %}
  </ul>

  {% load inclusion_tags %}
  {% include_part_of_html %}

{% endblock %}

templates/first_app/inclusion_html.html
<div>
  <p>{{ some_string }}</p>
  <p>{{ some_number }}</p>
  <p>{{ some_list }}</p>
</div>

templates/first_app/product_detail.html
{% extends 'base.html' %}

{% block page_title %}
	{{ block.super }} {{ product.title }}
{% endblock %}

{% block page_header %}
	{{ product.title }}
{% endblock %}

{% block content %}
  <ul>
  <li>{{ product.title }}</li>
  <li>{{ product.description }}</li>
  </ul>
{% endblock %}

templates/first_app/template.html
{% extends 'base.html' %}

{% block page_title %}
	{{ block.super }} Template page
{% endblock %}

{% block page_header %}
	Template page header
{% endblock %}

{% block content %}
	Some content
  <ul>links:
    <li><a href="{% url 'first_app:index' %}">Link to index</a></li>
  </ul>
  {% if users %}
    <ul>Users: {{ users|length }}
    {% for user in users %}
  	  <li>
        {{ forloop.counter }}. {{ user.name }}, {{ user.age }} ({{ user.phone }})
      </li>
    {% endfor %}
    </ul>
  {% endif %}


{% endblock %}